# fly.toml app configuration file generated for dungeonmarch-bot on 2024-04-14T18:27:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dungeonmarch-bot'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['app']
  min_machines_running = 1  # keep a machine running at all times


[[vm]]
  size = 'shared-cpu-1x'
