# fly.toml file generated for costilla on 2023-01-04T20:25:03-03:00

app = "costilla"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true


